# FAISS for TEXT - Quick Start
This notebook is a companion of chapter 2 of the "Domain Specific LLms in Action" book, author Guglielmo Iozzia, [Manning Publications](https://www.manning.com/), 2024.  
The code in this notebook is to introduce readers to the [FAISS](https://faiss.ai/index.html) library. No hardware acceleration required to execute all the code cells.

Install the missing required packages in the Colab VM. Only FAISS for CPU is missing. Then downgrade the now available [SentenceTransformers](https://www.sbert.net/) release to 4.1.0 for compatibility with the code in this notebook.

In [1]:
!pip install faiss-cpu
!pip uninstall sentence-transformers
!pip install sentence-transformers==4.1.0

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from faiss-cpu) (26.0)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 137.4 MB/s  0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3
WARNING: Skipping sentence-transformers as it is not installed.
Collecting sentence-transformers==4.1.0
  Downloading sentence_transformers-4.1.0-py3-none-any.whl.metadata (13 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers==4.1.0)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: tqdm in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sentence-transformers==4.1.0) (4.68.1)
Requirement already satisfied: torch>=1.11.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sentence-transformers==4.1.0) (2.8.0+cu128)
Requirement already satisfied: scikit-learn in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sentence-transformers==4.1.0) (1.3.2)
Requirement already satisfied: scipy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sentence-transformers==4.1.0) (1.11.4)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers==4.1.0)
  Downloading huggingface_hub-1.19.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: Pillow in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sentence-transformers==4.1.0) (12.2.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sentence-transformers==4.1.0) (4.15.0)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (3.29.1)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (6.0.3)
Collecting regex!=2019.12.17 (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0)
  Downloading regex-2026.5.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: requests in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (2.34.2)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting safetensors>=0.4.3 (from transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0)
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers==4.1.0) (2026.4.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub>=0.20.0->sentence-transformers==4.1.0)
  Downloading hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (82.0.1)
Requirement already satisfied: sympy>=1.13.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (1.14.0)
Requirement already satisfied: networkx in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers==4.1.0) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers==4.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch>=1.11.0->sentence-transformers==4.1.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers==4.1.0) (2026.5.20)
Requirement already satisfied: joblib>=1.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from scikit-learn->sentence-transformers==4.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from scikit-learn->sentence-transformers==4.1.0) (3.6.0)
Downloading sentence_transformers-4.1.0-py3-none-any.whl (345 kB)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 180.8 MB/s  0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 44.4 MB/s  0:00:00
Downloading hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 194.6 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 176.7 MB/s  0:00:00
Downloading regex-2026.5.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.2/801.2 kB 72.3 MB/s  0:00:00
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Installing collected packages: safetensors, regex, hf-xet, huggingface-hub, tokenizers, transformers, sentence-transformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [sentence-transformers]ence-transformers]
Successfully installed hf-xet-1.5.1 huggingface-hub-0.36.2 regex-2026.5.9 safetensors-0.8.0 sentence-transformers-4.1.0 tokenizers-0.22.2 transformers-4.57.6

Import the necessary packages/classes.

In [3]:
"""Module to cluster embeddings and create indices."""
import faiss

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

Set the data corpus for this example and put it into a Pandas DataFrame.

In [6]:
data = [['His secret identity is Peter Parker', 'spiderman'],
        ['A businessman and engineer who ' +
         'runs the company Stark Industries',
         'ironman'],
        ['Superhuman spider-powers and abilities ' +
         'after being bitten by a radioactive spider',
         'spiderman'],
        ['A frail man enhanced to the peak of human ' +
         'physical perfection by an experimental super-soldier serum', 'captainamerica']
        ]
df = pd.DataFrame(data, columns = ['text', 'context'])
df.head(10)

                                                text         context
0                His secret identity is Peter Parker       spiderman
1  A businessman and engineer who runs the compan...         ironman
2  Superhuman spider-powers and abilities after b...       spiderman
3  A frail man enhanced to the peak of human phys...  captainamerica

Get embeddings from the data corpus, generate a FAISS index and add the embeddings to it (after normalization).  
To make the code in the cell below compatible with SentenceTransformers release 5.0+, simple replace the line  
```vectors = encoder.encode(text)```  
with  
```vectors = encoder.encode(text.to_list())```

In [8]:
text = df['text']
encoder = SentenceTransformer("paraphrase-mpnet-base-v2")
vectors = encoder.encode(text)
vector_dimension = vectors.shape[1]
print('vector_dimension===>', vector_dimension)
l2_index = faiss.IndexFlatL2(vector_dimension)
faiss.normalize_L2(vectors)
l2_index.add(vectors)

vector_dimension===> 768

Prepare a search text to be used for similarity search with FAISS on the generated index.

In [28]:
# search_text = 'He throws webs'
# search_text = 'He is a super-soldier'
search_text = 'He is a super-soldier and hrows webs' 
search_vector = encoder.encode(search_text)
search_vector_as_array = np.array([search_vector])
faiss.normalize_L2(search_vector_as_array)

Perform a search within the created index (calculation of the distances between the search text and the strings within the index).

In [29]:
k = l2_index.ntotal
distances, ann = l2_index.search(search_vector_as_array, k=k)

Prepare the results to be displayed in a user-friendly format.

In [30]:
search_results = pd.DataFrame({'distances': distances[0], 'ann': ann[0]})
search_results.head()

   distances  ann
0   0.913094    3
1   1.180928    0
2   1.305882    1
3   1.314257    2

In [31]:
merged_df = pd.merge(search_results, df, left_on='ann', right_index=True)
merged_df.head()

,distances,ann,text,context
0,0.913094,3,A frail man enhanced to the peak of human phys...,captainamerica
1,1.180928,0,His secret identity is Peter Parker,spiderman
2,1.305882,1,A businessman and engineer who runs the compan...,ironman
3,1.314257,2,Superhuman spider-powers and abilities after b...,spiderman